#version of MySQL used = 5.7
#latest version of drupal is used

version: "3"
services:
  database:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: pallabi
      MYSQL_PASSWORD: roy
      MYSQL_DATABASE: mydatabase

  drupal:
    image: drupal:latest
    restart: always
    depends_on:
      - database
    ports:
      -8080:80
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: pallabi
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: roy
    volumes:
      - drupal_storage:/var/www/html
    
volumes:
  mysql_storage:
  drupal_storage:
